export const stateList = [
    { id: 1, value: 'AL', label: 'Alabama' },
    { id: 2, value: 'AK', label: 'Alaska' },
    { id: 3, value: 'AZ', label: 'Arizona' },
    { id: 4, value: 'AR', label: 'Arkansas' },
    { id: 5, value: 'CA', label: 'California' },
    { id: 6, value: 'CO', label: 'Colorado' },
    { id: 7, value: 'CT', label: 'Connecticut' },
    { id: 8, value: 'DE', label: 'Delaware' },
    { id: 9, value: 'DC', label: 'District Of Columbia' },
    { id: 10, value: 'FL', label: 'Florida' },
    { id: 11, value: 'GA', label: 'Georgia' },
    { id: 12, value: 'HI', label: 'Hawaii' },
    { id: 13, value: 'ID', label: 'Idaho' },
    { id: 14, value: 'IL', label: 'Illinois' },
    { id: 15, value: 'IN', label: 'Indiana' },
    { id: 16, value: 'IA', label: 'Iowa' },
    { id: 17, value: 'KS', label: 'Kansas' },
    { id: 18, value: 'KY', label: 'Kentucky' },
    { id: 19, value: 'LA', label: 'Louisiana' },
    { id: 20, value: 'ME', label: 'Maine' },
    { id: 21, value: 'MD', label: 'Maryland' },
    { id: 22, value: 'MA', label: 'Massachusetts' },
    { id: 23, value: 'MI', label: 'Michigan' },
    { id: 24, value: 'MN', label: 'Minnesota' },
    { id: 25, value: 'MS', label: 'Mississippi' },
    { id: 26, value: 'MO', label: 'Missouri' },
    { id: 27, value: 'MT', label: 'Montana' },
    { id: 28, value: 'NE', label: 'Nebraska' },
    { id: 29, value: 'NV', label: 'Nevada' },
    { id: 30, value: 'NH', label: 'New Hampshire' },
    { id: 31, value: 'NJ', label: 'New Jersey' },
    { id: 32, value: 'NM', label: 'New Mexico' },
    { id: 33, value: 'NY', label: 'New York' },
    { id: 34, value: 'NC', label: 'North Carolina' },
    { id: 35, value: 'ND', label: 'North Dakota' },
    { id: 36, value: 'OH', label: 'Ohio' },
    { id: 37, value: 'OK', label: 'Oklahoma' },
    { id: 38, value: 'OR', label: 'Oregon' },
    { id: 39, value: 'PA', label: 'Pennsylvania' },
    { id: 40, value: 'RI', label: 'Rhode Island' },
    { id: 41, value: 'SC', label: 'South Carolina' },
    { id: 42, value: 'SD', label: 'South Dakota' },
    { id: 43, value: 'TN', label: 'Tennessee' },
    { id: 44, value: 'TX', label: 'Texas' },
    { id: 45, value: 'UT', label: 'Utah' },
    { id: 46, value: 'VT', label: 'Vermont' },
    { id: 47, value: 'VA', label: 'Virginia' },
    { id: 48, value: 'WA', label: 'Washington' },
    { id: 49, value: 'WV', label: 'West Virginia' },
    { id: 50, value: 'WI', label: 'Wisconsin' },
    { id: 51, value: 'WY', label: 'Wyoming' },
];  


export const levelList = [
    { id: 1, value: 'Elementary', label: 'Elementary Schools' },
    { id: 2, value: 'Middle', label: 'Middle Schools' },
    { id: 3, value: 'High', label: 'High Schools' },
    { id: 4, value: 'Alt', label: 'Alternate Schools' },
    { id: 5, value: 'Public', label: 'Public Schools' },
    { id: 6, value: 'Private', label: 'Private Schools' },
];
